version: '2'

services:

   mysql:
     image: mariadb:latest
     container_name: mysql
     ports:
      - "3336:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: mpsLGtRe9HnS5mrd
     volumes:
       - db_data:/var/lib/mysql

   wordpress-es:
     depends_on:
       - mysql
     image: wordpress:latest
     container_name: wordpress-es
     ports:
       - "80:80"
       - "443:443"
     restart: always
     environment:
       WORDPRESS_DB_PASSWORD: mpsLGtRe9HnS5mrd
       WORDPRESS_DB_HOST: mysql
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - wp_data_es:/var/www/html
       
volumes:
    db_data:
      external:
        name: /volumes/mysql
    wp_data_es:
      external:
        name: /volumes/wordpress-es