version: '2'

services:

   mysql:
     image: mariadb:latest
     container_name: mysql
     ports:
      - "3306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: mpsLGtRe9HnS5mrd
     volumes:
       - ~/mysql-disk:/var/lib/mysql:rw

   wordpress-es:
     depends_on:
       - mysql
     image: arturopala/wordpress-ssl:latest
     container_name: wordpress-es
     ports:
       - "80:80"
       - "443:443"
     restart: always
     environment:
       WORDPRESS_DB_PASSWORD: mpsLGtRe9HnS5mrd
       WORDPRESS_DB_HOST: mysql
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - ~/wordpress-es-disk:/var/www/html:rw
       - ~/letsencrypt-es-disk:/var/www/letsencrypt/live:rw
   
