apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - image: mysql:5.6
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mpsLGtRe9HnS5mrd
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

  volumes:
    - name: mysql-persistent-storage
      gcePersistentDisk:
        # This GCE persistent disk must already exist.
        pdName: mysql-disk
        fsType: ext4
