apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pl
  labels:
    name: wordpress-pl
spec:
  containers:
    - image: wordpress
      name: wordpress
      env:
        - name: WORDPRESS_DB_PASSWORD
          value: mpsLGtRe9HnS5mrd
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_NAME
          value: wordpress_pl
      ports:
        - containerPort: 80
          name: wordpress
      volumeMounts:
        - name: wordpress-pl-persistent-storage
          mountPath: /var/www/html

  volumes:
    - name: wordpress-pl-persistent-storage
      gcePersistentDisk:
        # This GCE persistent disk must already exist.
        pdName: wordpress-pl-disk
        fsType: ext4
