apiVersion: v1
kind: Pod
metadata:
  name: wordpress-es
  labels:
    name: wordpress-es
spec:
  containers:
    - image: wordpress
      name: wordpress
      env:
        - name: WORDPRESS_DB_PASSWORD
          value: mpsLGtRe9HnS5mrd
        - name: WORDPRESS_DB_HOST
          value: wordpress-es
      ports:
        - containerPort: 80
          name: wordpress
      volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html

    - image: mysql:5.6
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mpsLGtRe9HnS5mrd
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

  volumes:
    - name: wordpress-persistent-storage
      gcePersistentDisk:
        # This GCE persistent disk must already exist.
        pdName: wordpress-disk
        fsType: ext4

    - name: mysql-persistent-storage
      gcePersistentDisk:
        # This GCE persistent disk must already exist.
        pdName: mysql-disk
        fsType: ext4
